env:
  es2021: true
  node: true
  browser: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/no-extraneous-dependencies: 
    error,
    devDependencies: 0
}
